### PR TITLE
Major refactor and implement https://arxiv.org/abs/1710.08969

### PR DESCRIPTION
**Pull request by r9y9**
- Decouple seq2seq and postnet
- Support training seq2seq and postnet separately

### CODE REVIEW

**Comment by r9y9** [comment]
Okay, found that separate training doesn't work nicely.

**Comment by r9y9** [comment]
Okay, it's basically working now

**Comment by r9y9** [comment]
[0_checkpoint_step000135000.wav.zip](https://github.com/r9y9/deepvoice3_pytorch/files/1486707/0_checkpoint_step000135000.wav.zip)

0_checkpoint_step000135000_alignment

**Comment by r9y9** [comment]
Learned alignment animation. Quickly become monotonic. Found that it's very noisy for zero padded regions, not sure if it matters

test

**Comment by rafaelvalle** [comment]
Thanks for putting this together! I can't wait to try it.
Would you say the current stage of the coda is stable and produces good outputs?

**Comment by r9y9** [comment]
I'm running a couple of experiments now, so please wait a moment. When I merge the PR, I would say that the model described in https://arxiv.org/abs/1710.08969 I implemented produces good outputs. From my perspective, it's better than (single speaker) DeepVoice3.

**Comment by r9y9** [comment]
Now that

```
python train.py --data-root=./data/ljspeech --checkpoint-dir=checkpoints_nyanko \
    --hparams="use_preset=True,builder=nyanko" \
    --log-event-path=log/nyanko_preset
```

should build a model produces good speech samples in 10 ~ 20 hours. Samples are https://www.dropbox.com/sh/q9xfgscgh3k5lqa/AACPgWCprBfNgjRravscdDYCa?dl=0.

**Pull request merged**
