### PR TITLE
Add flake8 to the testing

### PR DESCRIPTION
**Pull request by cclauss**
To automate the discovery of issues like #73 and #74 
* https://travis-ci.org/r9y9/deepvoice3_pytorch/builds/371514640#L762-L779

### CODE REVIEW

**Comment by r9y9** [comment]
Having automate flake8 is nice, but I'm not sure if `--select=E901,E999,F821,F822,F823` is good. Is this a standard in a certain community? Why did you use that?

**Comment by cclauss** [comment]
My sense is that E901,E999,F821,F822,F823 are the "showstopper" flake8 issues that can halt the runtime with a SyntaxError, NameError, etc. The other flake8 issues are merely "style violations" -- useful for readability but they do not effect runtime safety.

**Comment by cclauss** [comment]
If you want to clean up ALL the issues from the second flake8 run and then require the code to pass ALL flake8 tests then I have no objection to that.

**Comment by r9y9** [comment]
Got it, thanks for the explanation. Merging.

**Pull request merged**
